let data = [
  {
    _id: "66c05fd5bfc9145a5302d53e",
    title:
      "The Hôtel de Païva - The incredible destiny of the Marquise of the Champs-Elysées",
    vendorId: "66c0548ebfc9145a5302d52e",
    providers: [],
    description:
      "<p>The Hôtel de Païva, whose façade on the Champs Elysées is barely noticeable, is one of the most beautiful examples of private architecture and interior decoration under Napoleon III. It is due to the triumphant rise of one of the most noted adventurers of the 19th century: the Marquise de Païva.<br>​<br>Let's follow in the footsteps of the most adulated courtesan of the Second Empire. I will tell you her story, her famous affairs, her beauty secrets.<br><br>The private mansion, which took ten years to build, now welcomes businessmen from all over the world, members of the very private Travellers Club.<br><br>During the visit, I will show you the decoration of the ostentatiously luxurious lounges where marble and gilding are abundant, the superb onyx staircase as well as the silver-plated bronze bathtub.</p>",
    address: "Avenue des Champs-Élysées ",
    price: [],
    duration: ["2h"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions: "",
    storyLineKeywords: [
      "Hôtel de Païva",
      "Champs Elysées",
      "Travellers Club",
      "Private Palace",
      "Napoleon III",
      "Second Empire",
    ],
    memberShip: "bronze",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66c0606abfc9145a5302d53f",
    title:
      "The Perfume - What could Paris have smelled like in the 18th century?",
    vendorId: "66c0548ebfc9145a5302d52e",
    providers: [],
    description:
      '<p>What if Paris had a smell? For some, "Paris smells of honey", "the RER B platform", "the Luxembourg gardens" and for you?<br><br>Did you like Patrick Süskind\'s novel? You will love this perfumed and creative walk, the first visit in "odorama" to smell and feel the air of Paris with real perfume essences. They say that Parisians have a nose. Do like the hero of the book Jean-Baptiste Grenouille and discover the lively and enticing olfactory landscape of the largest reserve of odors in the world: the city of Paris in the 18th century.<br><br>This unique experience-tour invites you to relive the plot of the famous novel in the magical center of the capital. You follow in the footsteps of the genius from the popular district of Les Halles to the Bourgeois Paris of Saint-Germain-des-Près. Immerse yourself in the scents of wig powder, carriage leather, tuberoses in the carriage entrances... Inhale the fetid odors of the cemetery of the Innocents and the whiffs of the tanneries on the banks of the Seine. Finally, discover the arrogant voluptuousness of rococo perfumes...</p><p>This visit will continue in the workshop of a Parisian perfumer in a private apartment on the Ile Saint-Louis. Embark on an olfactory journey of 1h30. You will discover the mysteries of distillation and then train your nose to new scents. You will select those that you like the most and you will create, like the brilliant Jean-Baptiste Grenouille, your own perfume: a unique perfume, the one that suits you!</p>',
    address: "",
    price: [],
    duration: ["2h"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    linkWithOtherService: [],
    termsAndConditions: "",
    storyLineKeywords: [
      "Perfume",
      "Les Halles",
      "Saint-Germain-des-Pres",
      "Patrick Süskind",
      "Jean-Baptiste Grenouille",
      "Perfume tour",
      "Perfume workshop",
    ],
    memberShip: "bronze",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66c061b9bfc9145a5302d541",
    title:
      "Art Deco according to Jeanne Lanvin - the sumptuous apartment of the Parisian designer",
    vendorId: "66c0548ebfc9145a5302d52e",
    providers: [],
    description:
      '<p>22, rue du Faubourg Saint-Honoré... The legendary address of the Lanvin house, symbol of femininity and elegance, is today a prestigious brand recognized throughout the world. Jeanne Lanvin, a visionary designer, was also an exceptional woman.<br>Born in 1867, she decided from her childhood to turn her destiny towards the fashion world. A milliner at 16, she developed a passion for hats. She quickly opened her own workshop and in 1925, she already employed more than 800 seamstresses.<br><br>This visit invites you to discover a lesser-known side of the seamstress: her taste for interior decoration.<br>In 1920, Jeanne Lanvin bought the former private mansion of the Marquise Arconati-Visconti, 16 rue Barbet-de-Jouy. She had a reception wing built whose rooms were designed by Armand-Albert Rateau. In the 1920s, this decorator developed a very particular style that arose from his interest in ancient art and the use of an original bestiary.<br>The three rooms of Jeanne Lanvin\'s private apartment, also decorated by Rateau in 1924-1925, illustrate a very personal luxury with its furniture in bronze with an antique patina, in oak or in gilded wood.<br>​<br>The visit will continue with the discovery of the "art deco" collections at the MAD (Musée des Arts Décoratifs)</p>',
    address: "Musée des Arts Décoratifs",
    price: [],
    duration: ["2h"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions: "",
    storyLineKeywords: [
      "Jeanne Lanvin",
      "Coco Chanel",
      "Art Deco",
      "1920",
      "Fashion",
      "Private apartment",
    ],
    memberShip: "bronze",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66c06287bfc9145a5302d542",
    title: "Vendome Chic - The History of Haute Couture and Haute Joaillerie",
    vendorId: "66c0548ebfc9145a5302d52e",
    providers: [],
    description:
      "<p>Cartier, Mauboussin, Van Cleef &amp; Arpels, Boucheron… More than a century ago, these legendary Haute-joaillerie houses set up shop on Place Vendôme and seduced the prestigious clientele of the Ritz with their exceptional sets. Produced on site, the sublime pieces composed of the most sumptuous stones and diamonds attracted princesses and aristocrats from all over the world.<br><br>Alongside them, the couturiers Frédéric Worth, Coco Chanel, Jacques Doucet, Jeanne Paquin and Paul Poiret made the coveted French elegance shine. Their creations, which combined audacity and tradition, called upon all the finesse of an exceptional Haute-couture.<br><br>A few steps further, the streets of Paix, Castiglione and Cambon have seen famous clients, icons of their eras: Marcel Proust, Charles Baudelaire, Jean Cocteau, Sarah Bernhardt, or Françoise Sagan…<br><br>Thanks to a unique know-how carefully preserved and to innovative and assertive styles, these jewelers, creators and personalities have contributed to building the international reputation of Paris as the capital of luxury and fashion.</p>",
    address: "Place Vendome",
    price: [],
    duration: ["2h"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions: "",
    storyLineKeywords: [
      "Fashion",
      "Haute Couture",
      "Luxury Shopping",
      "Jewellery ",
      "Cartier",
      "Mauboussin",
      "Van Cleef & Arpels",
      "Boucheron",
      "Place Vendome",
      "Ritz Hotel",
      "Frédéric Worth",
      "Coco Chanel",
      "Marcel Proust",
      "Jean Cocteau",
    ],
    memberShip: "bronze",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66c065a4bfc9145a5302d543",
    title: "The legendary house of Dior",
    vendorId: "66c0548ebfc9145a5302d52e",
    providers: [],
    description:
      '<p>Dior, a name that rhymes with prestige, perfection and elegance. In the 50s, Christian Dior signed a fashion revival with his "Corolle" collection and his "New-Look" look. The couturier redesigned the body: high chest, slim waist and blossoming hips. "All of Paris" was stunned by this profusion of fabrics and colors. After a career as a gallery owner, illustrator and then model maker for the house of Lelong, he launched his own brand in February 1947. In just seven months, he created a collection that became the showcase of his boutique. Dior aimed for perfection, refused to restrict himself. For him, the dress is the ephemeral architecture intended to exalt the body of women. The gifted designer teamed up with Michel Boussac, the "king of cotton", to design increasingly long dresses; he gave women back their frivolity. At the end of the 1940s, the discreet man established himself as the new messiah of fashion. He was the first couturier to make the cover of Time magazine. His brand became the essential reference in terms of luxury and French chic.<br>During this visit, we will focus on the store at 30 avenue Montaigne. His boutique, which has become legendary, was inspired by his birthplace in Granville. This family home with its understated elegance would still inspire his perfume “Miss Dior”. Today, the Hôtel Dior is still part of this heritage.<br>For all fashion enthusiasts, come and meet the illustrious couturier with his unique creations, and discover the secrets of the house of Dior, synonymous with renewal, beauty and escape.</p>',
    address: "Avenue Montaigne",
    price: [],
    duration: ["2h"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [
      {
        experienceId: "66c055b6bfc9145a5302d52f",
        experienceName: "Private Visit of Parisian Districts",
        why: "Great addition to the Avenue Montaigne visit",
      },
    ],
    termsAndConditions: "",
    storyLineKeywords: [
      "DIor",
      "Fashion",
      "Haute Couture",
      "Luxury Shopping",
      "Avenue Montaigne",
    ],
    memberShip: "silver",
  },
  {
    _id: "66c06650bfc9145a5302d544",
    title: "Coco Chanel's Paris",
    vendorId: "66c0548ebfc9145a5302d52e",
    providers: [],
    description:
      '<p>Il était une fois Gabrielle Chanel, une jeune femme qui masqua ses origines paysannes et créa sa propre légende Haute-couture, aidée par "Boy" Capel, son amour britannique. Symbole de&nbsp;l’élégance à la française&nbsp;dans le monde, Coco Chanel brisa les codes et&nbsp;libéra les corps&nbsp;de la femme moderne.&nbsp;<br>Fondée en 1910, la maison Chanel créa la nouvelle silhouette féminine, une révolution stylistique. Les chevilles devinrent apparentes, la taille délivrée du corset, la peau bronzée, les cheveux coupés. Au cœur des années folles, la jeune créatrice redessina la silhouette de la parisienne : la tenue&nbsp;« sportswear chic », la fameuse&nbsp;petite robe noire&nbsp;et sa fragrance audacieuse&nbsp;Chanel « n°5 ».&nbsp;Ces pièces résistaient aux modes et au temps qui passe, la sobriété devint le gage de l’indémodable. La visite s’intéressera de plus près aux secrets de la&nbsp;rue Cambon, dans la maison Chanel, l’adresse parisienne où Coco posa ses valises en 1918 avant de s’installer&nbsp;au Ritz Place Vendôme&nbsp;où elle s’éteignit en 1971.<br><br>Retraçons l’histoire de la marque Chanel, des créations de Coco aux mythiques tailleurs de&nbsp;Karl Lagerfeld.<br><br>Nous aborderons également l’aspect contemporain de la marque par&nbsp;Virginie Viard,&nbsp;nouvelle créatrice de la maison Chanel. Redécouvrons cette maison de prestige et du luxe à la française.</p>',
    address: "",
    price: [],
    duration: ["90mins"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [
      {
        experienceId: "66c065a4bfc9145a5302d543",
        experienceName: "The legendary house of Dior",
        why: "Great combination for fashion lovers",
      },
      {
        experienceId: "66c055b6bfc9145a5302d52f",
        experienceName: "Private Visit of Parisian Districts",
        why: "Great addition to the Place Vendome tour",
      },
    ],
    termsAndConditions: "",
    storyLineKeywords: [
      "Coco Chanel",
      "Karl Lagerfeld",
      "Ritz Hotel",
      "Fashion",
      "Haute Couture",
      "Luxury Shopping",
    ],
    memberShip: "silver",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66c06701bfc9145a5302d545",
    title: "The Yves Saint Laurent Museum",
    vendorId: "66c0548ebfc9145a5302d52e",
    providers: [],
    description:
      '<p>"The most beautiful garment that can dress a woman is the arms of the man she loves. But, for those who have not had the chance to find this happiness, I am here."</p><p>Meet this visionary artist, born in Algeria in 1936 and trained with the great Christian Dior. Yves-Saint-Laurent succeeded him at only 21 years old. He then enjoyed considerable success by founding his own brand, accompanied by Pierre Bergé, the love of his life.<br>From there, his first collections and his first fashion show were born in 1962 with his “Trapèze” dress. Feminist and committed, he designed the famous women’s tuxedo, inspired by the men’s wardrobe. His collections aroused interest in the midst of the sexual revolution. His avant-garde style liberated the woman’s body: she was, in his eyes, conquering and rebellious, like Catherine Deneuve. The actress became his muse and his great friend. Keen to democratize fashion, he launched his ready-to-wear line in 1966. Provocative, he designed his “Libération” collection in the 1970s, inspired by years of war. It caused a scandal and was violently criticized by the press. It still leaves its mark today. Decorated and Oscar-winning, he passed away in 2008 from a tumor.<br>A look back at the unique career of this gifted designer at the Yves Saint Laurent Museum, the historic site of his former fashion house from 1974 to 2002. Come and admire the wealth of heritage preserved by the Pierre Bergé Foundation in the original atmosphere of the brand through thematic exhibitions that reflect the creative genius and the manufacturing process of the Haute Couture collections.<br>Follow me through this unique place to meet the gifted artist and his creations preserved by the Pierre Bergé – Yves Saint Laurent Foundation.</p>',
    address: "",
    price: [],
    duration: ["90 mins"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [
      {
        experienceId: "66c065a4bfc9145a5302d543",
        experienceName: "The legendary house of Dior",
        why: "Perfect combination for fashion lovers as Saint Laurent trained at Dior",
      },
      {
        experienceId: "66c055b6bfc9145a5302d52f",
        experienceName: "Private Visit of Parisian Districts",
        why: "Perfect addition to the Avenue Montaigne tour",
      },
      {
        experienceId: "66c06650bfc9145a5302d544",
        experienceName: "Coco Chanel's Paris",
        why: "Great for fashion lovers",
      },
    ],
    termsAndConditions: "",
    storyLineKeywords: [
      "Yves Saint Laurent",
      "Fashion",
      "Luxury Shopping",
      "Dior",
      "Avenue Montaigne",
    ],
    memberShip: "bronze",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66c068c1bfc9145a5302d546",
    title:
      "A Gourmand's Promenade - A delicious getaway around exquisite pastries",
    vendorId: "66c0548ebfc9145a5302d52e",
    providers: [],
    description:
      "<p>Let's awaken our taste buds and discover French know-how through a tasteful journey. Let's admire together the refined creations of couture pastries. Between tradition and avant-garde, you will be surprised by the richness of the flavors of these little luxuries.<br>​<br>Cédric Grolet, Pierre Marcolini, Stohrer, Patrick Roger, Arnaud Larher, Christophe Michalak... These big names in pastry offer us unique and quality products. Thanks to a prestigious selection of ingredients, they innovate and rework the techniques and styles of yesteryear. Finesse and precision make these little pleasures tailor-made creations, as desirable as haute couture pieces!<br><br>Thanks to different stops, this walk will take you to all the good addresses of gourmet Paris.</p>",
    address: "",
    price: [],
    duration: ["2h"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions: "",
    storyLineKeywords: [
      "Pastries",
      "Desserts",
      "Cédric Grolet",
      "Pierre Marcolini",
      "Ladurée",
    ],
    memberShip: "bronze",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66c0693dbfc9145a5302d547",
    title: "Behind the scenes of the old addresses of Parisian prostitution",
    vendorId: "66c0548ebfc9145a5302d52e",
    providers: [],
    description:
      "<p>Partons ensemble sur les traces des maisons closes parisiennes d'autrefois. Cette visite vous présentera les plus grands établissements autour du&nbsp;Palais Royal, origine géographique de la prostitution à Paris.&nbsp;<br><br>Nous plongerons dans la vie quotidienne atypique des femmes de ces célèbres lieux de plaisir :&nbsp;Le Chabanais,&nbsp;Le Colbert, Le Panier Fleuri... Nous évoquerons aussi des clients importants, comme le roi&nbsp;Edouard VII&nbsp;et nous reviendrons sur les parcours de courtisanes aux réputations sulfureuses.&nbsp;<br>​<br>Découvrons un univers très privé, chargé d'Histoire.&nbsp;&nbsp;<br>Une visite initialement créée pour le lancement de la deuxième saison de la série de Canal + 'Maison Close'.</p>",
    address: "",
    price: [],
    duration: ["2h"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions: "<p>Not suitable for children under 15</p>",
    storyLineKeywords: [
      "Old pleasure houses",
      "Palais Royal",
      "Adults",
      "Edward VII",
      "Erotic",
    ],
    memberShip: "bronze",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66c06a29bfc9145a5302d548",
    title: "Hôtel de Lauzun - three centuries of history in a sumptuous palace",
    vendorId: "66c0548ebfc9145a5302d52e",
    providers: [],
    description:
      "<p>Who are the walkers along the banks of the Seine who know about this exceptional residence?<br>Behind the heavy doors of number 17 Quai d'Anjou lies an architectural gem. Composed of a series of rooms with gilded decorations and ceilings comparable to those of the Château de Vaux-le-Vicomte.<br><br>The Hôtel de Lauzun, built in 1657 for the financier Charles Grüyn des Bordes, preserves the best-preserved reception apartment of the Grand Siècle. This Parisian “Little Versailles” houses a unique set of opulent decorations with a thousand fancies.<br><br>This exclusive private visit takes you into a place rarely open to the public. I will reveal its decorations to you: its superb balcony in gilded wrought iron, its main courtyard and its sundial, the main staircase, its splendid apartment in a row...<br><br>I will tell you its historical secrets: the financial intrigues of the court of Louis XIV; the orgies of the Duke of Lauzun, adventurer and lover of the king's cousin La Grande Mademoiselle; the \"artificial paradises\" of Charles Baudelaire and the crazy evenings of the Haschichins club.</p>",
    address: "",
    price: [],
    duration: [],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [
      {
        experienceId: "66c055b6bfc9145a5302d52f",
        experienceName: "Private Visit of Parisian Districts",
        why: "Perfect to complete the Saint Louis Island walk",
      },
    ],
    termsAndConditions: "",
    storyLineKeywords: [
      "Ile Saint Louis",
      "Private Palace",
      "duc de Lauzun",
      "Charles Baudelaire",
    ],
    memberShip: "",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "65ff3cfd8302531638e39728",
    title: "Private Diner in the Palace",
    vendorId: "65ff02c2e1b82f7ea737f8e3",
    providers: [
      {
        providerId: "65ff3f798302531638e3972d",
        providerName: "Testing 204",
      },
    ],
    description:
      "<p>Enjoy the rare privilege of dining inside the Palace of Versailles. A gastronomic meal will be served in one of the small apartments</p>",
    address: "Versailles",
    price: ["€15000"],
    duration: ["90 mins"],
    availableTime: ["Tuesday to Sunday from 7pm to 9:30pm"],
    links: [
      {
        link: "www",
        explanation: "Diner at the palace",
      },
      {
        link: "www.chef",
        explanation: "Chef",
      },
    ],
    linkWithOtherExperience: [
      {
        experienceId: "65ff0640e1b82f7ea737f8e4",
        experienceName: "",
        why: "Perfect to end the private visit by dining at the palace",
      },
    ],
    linkWithOtherService: [],
    termsAndConditions:
      "<p>Booking 4 weeks in advance minimum</p><p>Allergies and dietary restrictions required when booking</p>",
    storyLineKeywords: [
      "Versailles",
      "Hall of Mirrors",
      "Gastronomy",
      "Private Diner",
      "Exceptional Dining Experience",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66000cff3b3a2d7cf3c2c333",
    title: "Private Visit to the Trianon Estate",
    vendorId: "65ff02c2e1b82f7ea737f8e3",
    description:
      "<p>In an attempt to gain some brief respite from courtly etiquette, the kings of Versailles built themselves more intimate spaces close&nbsp;to the main palace. Adjoining the Petit Parc, the estate of Trianon&nbsp;is home to the Grand Trianon and Petit Trianon palaces, as well as the Queen’s Hamlet and a variety of ornamental gardens.</p><p>Enjoy an exclusive private visit of the entire estate to discover Marie Antoinette's Petit Trianon, her intimate QUeen's Theatre and bucolic Hamlet set within the English Garden, and the sumptuous Napoleon apartments at the Grand Trianon when some famous heads of state have stayed,&nbsp;including those of&nbsp;Queen Victoria&nbsp;in 1855. She visited Napoleon III in 1855., Tsar Nicholas II in 1896 and King George VI in 1938.</p>",
    address: "Versailles",
    price: ["€5000"],
    duration: ["90 mins"],
    availableTime: ["Tuesday to Sunday 6pm to 9pm", "Monday 11am to 9pm"],
    links: [
      {
        link: "https://en.chateauversailles.fr/discover/estate/estate-trianon",
        explanation: "Official website - The Estate of Trianon",
      },
    ],
    linkWithOtherExperience: [
      {
        experienceId: "65ff0e60e1b82f7ea737f8e5",
        experienceName: "Private Visit of the Small Apartments",
        why: "Complements the Marie Antoinette variation and the Napoleon Variation",
      },
    ],
    termsAndConditions: "<p>Booking minimum 3 weeks in advance</p>",
    storyLineKeywords: [
      "Versailles",
      "Royal Palace",
      "Napoleon",
      "Marie Antoinette",
      "English Garden",
      "Queen of France",
      "Louis XV",
      "Louis XVI",
      "Queen’s Hamlet",
      "Grand Trianon",
      "Petit Trianon",
      "Queen's Theatre",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66000f783b3a2d7cf3c2c334",
    title: "VIP Visit of the Palace's Gardens",
    vendorId: "65ff02c2e1b82f7ea737f8e3",
    description:
      "<p>Visitors looking through the central window in the Hall of Mirrors will see the Grande Perspective stretching away towards the horizon from the Water Parterre. This unique east-west perspective originally dates from before the reign of Louis XIV, but it was developed and extended by the gardener André Le Nôtre, who widened the Royal Way and dug&nbsp;the Grand Canal.\n<br>\n</p><p>In 1661 Louis XIV entrusted André Le Nôtre with the creation and renovation of the gardens of Versailles, which he considered just as important as the Palace. Work on the gardens was started at the same time as the work on the palace and lasted for 40 or so years. During this time André Le Nôtre collaborated with the likes of Jean-Baptiste Colbert, Superintendant of Buildings to the King from 1664 to 1683, who managed the project, and Charles Le Brun, who was made First Painter to the King in January 1664 and provided the drawings for a large number of the statues and fountains. Last but not least, each project was reviewed by the King himself, who was keen to see “every detail”. Not long after, the architect Jules Hardouin-Mansart, having been made First Architect to the King and Superintendant of Buildings, built the Orangery and simplified the outlines of the Park, in particular by modifying or opening up some of the groves.\n<br>\n</p><p>Creating the gardens was a monumental task. Large amounts of soil had to be shifted to level the ground, create parterres, build the Orangery and dig out the fountains and Canal in places previously occupied solely by meadows and marshes. Trees were brought in from different regions of France. Thousands of men, sometimes even entire regiments, took part in this immense project.\n</p><p><br>\nDiscover the palace’s majestic gardens during a VIP visit aided by one of the head gardeners of the palace and get the privilege of accessing what regular visitors can’t access.</p>",
    address: "Versailles",
    price: ["€2500 up to 10 people"],
    duration: ["2 hours and 30min"],
    availableTime: ["Monday to Sunday 10am to 7pm"],
    links: [
      {
        link: "https://en.chateauversailles.fr/discover/estate/gardens",
        explanation: "Official Website - The Gardens",
      },
    ],
    linkWithOtherExperience: [],
    termsAndConditions: "<p>Bookings minimum 3 weeks in advance</p>",
    storyLineKeywords: ["Versailles", "Royal Palace", "André Le Nôtre"],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "660010ed3b3a2d7cf3c2c335",
    title: "Private Visit of the Sculptures and Mouldings Gallery",
    vendorId: "65ff02c2e1b82f7ea737f8e3",
    providers: [],
    description:
      "<p>The Small Stables are home to various institutions as well as one of the finest sculpture storehouses for the Palace of Versailles and the Musée du Louvre. Copies of ancient Greek and Roman statues are stored under the late 17th century vaulted ceilings, side by side with original sculptures from the gardens of the Palace of Versailles.\n<br>\n</p><p>Enjoy a private access guided by a historian of the palace or the Louvre museum to discover this sculpture storehouse unique in the world.</p>",
    address: "Versailles",
    price: ["€2500"],
    duration: ["90 mins"],
    availableTime: ["Monday to Sunday 11am to 5pm"],
    links: [
      {
        link: "https://en.chateauversailles.fr/discover/estate/small-stables",
        explanation: "Official website - Small Stables",
      },
    ],
    linkWithOtherExperience: [],
    termsAndConditions: "<p>Bookings minimum 3 weeks in advance</p>",
    storyLineKeywords: [
      "Versailles",
      "Stables",
      "Sculptures museum",
      "Mouldings Gallery",
      "Ancient Greece",
      "Ancient Rome",
      "Louvre Museum",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "6600122a3b3a2d7cf3c2c336",
    title: "The Gallery of Coaches",
    vendorId: "65ff02c2e1b82f7ea737f8e3",
    description:
      "<p>Visiting the Gallery of Coaches in the Great Stables unveils the greatest royal construction project for housing horses ever undertaken. Majestic coaches and small carriages for Marie-Antoinette's children, sedan chairs and sleds make up a strange and wonderful collection. The exhibition of these creations is an amazing testimony to the pomp and splendour of court life during the Ancien Régime, the Empire and the Restoration.\n<br>\nEnjoy a private guided tour with a historian of the palace to discover this gallery</p>",
    address: "Versailles",
    price: ["€2500"],
    duration: ["60 mins"],
    availableTime: ["Tuesday to Sunday 10am to 12pm"],
    links: [
      {
        link: "https://en.chateauversailles.fr/discover/estate/great-stables/gallery-coaches",
        explanation: "Official Website - The Coaches Gallery",
      },
    ],
    linkWithOtherExperience: [],
    termsAndConditions: "<p>Bookings minimum 3 weeks in advance</p>",
    storyLineKeywords: [
      "Versailles",
      "Great Stables",
      "Marie Antoinette",
      "Louis XIV",
      "Hardouin-Mansart",
      "Louis-Philippe",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "660014913b3a2d7cf3c2c338",
    title: "Private Visit of the Academy",
    vendorId: "660013703b3a2d7cf3c2c337",
    description:
      "<p>Discover the magnificent historical enclosure of the Great Stable, a building remarkable for its size and the nobility of its architecture and the National Equestrian Academy with a private guided tour alongside a member of the academy</p>",
    address: "Versailles",
    price: ["€2500"],
    duration: ["60 mins"],
    availableTime: ["Monday to Sunday 10am to 4pm"],
    links: [
      {
        link: "https://www.bartabas.fr/academie-equestre-de-versailles/visites-du-lieu/?lang=en",
        explanation: "Official Website",
      },
    ],
    linkWithOtherExperience: [],
    termsAndConditions: "<p>Bookings minimum 3 weeks in advance</p>",
    storyLineKeywords: ["Versailles", "Equestrian Academy", "Horse Riding"],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "660016353b3a2d7cf3c2c339",
    title: "Attend a Dressage Training",
    vendorId: "660013703b3a2d7cf3c2c337",
    description:
      "<p>Enjoy the privilege of attending a dressage training with the Lusitanos of the Equestrian Academy to see the work of these world-renowned equerries work with their horses alongside a member of the academy.</p>",
    address: "Versailles",
    price: ["€3500"],
    duration: ["90 mins"],
    availableTime: ["Monday to Saturday 2pm to 5pm"],
    links: [
      {
        link: "no",
        explanation: "no",
      },
    ],
    linkWithOtherExperience: [
      {
        experienceId: "660014913b3a2d7cf3c2c338",
        experienceName: "Private Visit of the Academy",
        why: "Perfect complement to see the work with the horses",
      },
    ],
    termsAndConditions: "<p>Bookings minimum 3 weeks in advance\n<br><br></p>",
    storyLineKeywords: [
      "Versailles",
      "Equestrian Academy",
      "Lusitano",
      "Dressage",
      "Horse Training",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "660017dc3b3a2d7cf3c2c33a",
    title: "Riding Lesson at the Academy",
    vendorId: "660013703b3a2d7cf3c2c337",
    description:
      "<p>Have you ever imagine being able to ride with one of the most renowned equestrian academies in the world and learn from their equerries?&nbsp;\nDuring this private lesson, you will ride one of the academy’s lusitanos alongside an equerry in Versailles’ Great Stable. A unique opportunity to learn the art of dressage.</p>",
    address: "Versailles",
    price: ["€3000 per person"],
    duration: ["90 mins"],
    availableTime: ["Upon request"],
    links: [
      {
        link: "no",
        explanation: "no",
      },
    ],
    linkWithOtherExperience: [
      {
        experienceId: "660016353b3a2d7cf3c2c339",
        experienceName: "Attend a Dressage Training",
        why: "Get to ride a horse of the academy after seeing their training",
      },
    ],
    termsAndConditions:
      "<p>Bookings minimum 6 weeks in advance</p><p>Only available to advanced rider</p>",
    storyLineKeywords: [
      "Versailles",
      "Equestrian Academy",
      "Lusitano",
      "Riding Horse",
      "Private Lesson",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66001e6f3b3a2d7cf3c2c33e",
    title:
      "Private Visit of the Royal Tennis Court of Versailles - Jeu de Paume",
    vendorId: "65ff02c2e1b82f7ea737f8e3",
    description:
      "<p>On 20 June 1789, the Royal&nbsp;Tennis Court (Jeu de Paume) of Versailles played a major part in French history. From being a royal sports hall during the reign of Louis XIV, it became synonymous with the foundation of French democracy and will be forever linked to a key episode in the French Revolution.\n</p><p><br>\nDuring this exclusive private visit you will discover this historical landmark where, on 20 June 1789, the deputies of the Third Estate met there at the time of the Estates General, and took an oath not to separate until they had endowed France with a written constitution. This is known as the Tennis Court Oath, which kickstarted the French Revolution.</p>",
    address: "1 Rue du Jeu de Paume, 78000 Versailles",
    price: ["€1000"],
    duration: ["90 mins"],
    availableTime: ["Monday to Saturday 11am to 5pm"],
    links: [
      {
        link: "https://en.chateauversailles.fr/discover/estate/royal-tennis-court",
        explanation: "Official website",
      },
      {
        link: "https://en.wikipedia.org/wiki/Tennis_Court_Oath",
        explanation: "Wikipedia Link to the Tennis Court Oath",
      },
    ],
    linkWithOtherExperience: [
      {
        experienceId: "65ff0e60e1b82f7ea737f8e5",
        experienceName: "Private Visit of the Small Apartments",
        why: "Perfect addition to the French Revolution and the Marie Antoinette variation",
      },
    ],
    termsAndConditions: "<p>Bookings minimum 1 week in advance</p>",
    storyLineKeywords: [
      "Versailles",
      "French Revolution",
      "Real Tennis",
      "Jeu de Paume",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "660020003b3a2d7cf3c2c33f",
    title: "The Congress Chamber",
    vendorId: "65ff02c2e1b82f7ea737f8e3",
    description:
      '<p>Built at the end of the 19th century, the Congress Chamber is still used today by the members of the National Assembly and the Senate when they meet in a "Congress" to adopt constitutional amendments or to hear an address by the President of the Republic.\n</p><p><br>\nThis unique chamber isn’t open to the public, nor the Napoleon Vestibule and the Seal Room. During this private visit, you will be able to access these 3 rooms that play such a significant role in the French Republic.</p>',
    address: "Versailles",
    price: ["€5000"],
    duration: ["60 mins"],
    availableTime: ["Monday to Saturday 10am to 5pm"],
    links: [
      {
        link: "https://en.chateauversailles.fr/discover/estate/palace/congress-chamber#the-vestibule",
        explanation: "Official Website",
      },
    ],
    linkWithOtherExperience: [
      {
        experienceId: "65ff0e60e1b82f7ea737f8e5",
        experienceName: "Private Visit of the Small Apartments",
        why: 'Perfect addition to the variation "Versailles in the XIX Century"',
      },
    ],
    termsAndConditions: "<p>Bookings minimum 4 weeks in advance</p>",
    storyLineKeywords: [
      "Versailles",
      "Congress Chamber",
      "French Parliament",
      "French Constitution",
      "French President",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "660027013b3a2d7cf3c2c341",
    title: "Private visit of the Palais Garnier",
    vendorId: "660022683b3a2d7cf3c2c340",
    description:
      "<p>Designed by architect Charles Garnier in 1875, the Palais Garnier hosts a prestigious auditorium and various public areas (grand foyer, rotonde des abonnés, lounges), as well as a museum-library and different rehearsal studios and workshops.\n<br>\nThe Italian-style auditorium, with its ceiling painted in 1964 by Marc Chagall, can welcome 2054 spectators. With nearly 480,000 visitors each year, it is one of Paris' most visited monuments. It has been listed as a historical monument since 1923.&nbsp;\n<br>\nDuring this exclusive backstage and private visit, you will discover all the famous parts of the theatre that are accessible during the opera’s performances without the crowds, but also, you will also get to see what the public doesn’t get to see.&nbsp;\nThe backstage part of the visit will take you to the opera’s stage, to the Foyer de la Danse (the Dance Foyer) behind the stage, and several other secretive places.</p>",
    address: "Palais Garnier - Pl. de l'Opéra, 75009 Paris",
    price: ["€6500 up to 10 people"],
    duration: ["2 hour"],
    availableTime: ["Monday to Saturday 11am to 5pm"],
    links: [
      {
        link: "https://www.operadeparis.fr/en/about/theaters-and-workshops/palais-garnier",
        explanation: "Official website",
      },
    ],
    linkWithOtherExperience: [],
    termsAndConditions: "<p>Bookings minimum 2 weeks in advance</p>",
    storyLineKeywords: [
      "Paris Opera House",
      "Palais Garnier",
      "Charles Garnier",
      "Opera House",
      "Backstage Visit",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "660028e23b3a2d7cf3c2c342",
    title: "Private Visit of the Opera Bastille",
    vendorId: "660022683b3a2d7cf3c2c340",
    description:
      "<p>Inaugurated on 13 July 1989, the Bastille Opera house is the work of Uruguayan-Canadian architect Carlos Ott. The building is marked by transparent façades and the use of identical materials inside and outside the building.\n<br>\nThe Bastille Opera has developed state-of-the-art craftsmanship and technology. Devoted to the making of performances, hundreds of people are combining their efforts and skills throughout the year. An entire city comes to life: stage technicians, sculptors and painters, seamstresses and hairdressers work alongside the singers, dancers and musicians.\n<br>\nDuring this exclusive backstage and private visit, you will discover the backstages of this incredible “Opera City” to see the opera’s workshops, rehearsal spaces and backstages.</p>",
    address: "Opera Bastille - 120 rue de Lyon, 75012 Paris",
    price: ["€6500"],
    duration: ["2 hour"],
    availableTime: ["Monday to Friday 11am to 4pm"],
    links: [
      {
        link: "https://www.operadeparis.fr/en/about/theaters-and-workshops/bastille-opera",
        explanation: "Official Website",
      },
    ],
    linkWithOtherExperience: [],
    termsAndConditions: "<p>Bookings minimum 2 weeks in advance</p>",
    storyLineKeywords: [
      "Paris Opera House",
      "Backstage Visit",
      "Costumes workshops",
      "Set design workshops",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66002c1b3b3a2d7cf3c2c343",
    title: "Ballet's Costumes workshop - Palais Garnier",
    vendorId: "660022683b3a2d7cf3c2c340",
    description:
      "<p>The costumes workshops of the Palais Garnier host the ballet costumes production. It is a secretive and magical place where the opera’s expert sewers create the costumes for most of the ballet productions. <br>During this visit, you will get access to this very unique workshop to meet with the dressmaking artists of the Paris Opera House</p>",
    address: "Palais Garnier - Pl. de l'Opéra, 75009 Paris",
    price: ["€3500 up to 5 people"],
    duration: ["45 mins"],
    availableTime: ["Monday to Friday 11am to 5pm"],
    links: [
      {
        link: "https://www.operadeparis.fr/en/about/theaters-and-workshops/costumes-workshops",
        explanation: "Official Website",
      },
    ],
    linkWithOtherExperience: [
      {
        experienceId: "660027013b3a2d7cf3c2c341",
        experienceName: "Private visit of the Palais Garnier",
        why: "Completes the backstage visit of the Palais Garnier. Highly exclusive",
      },
    ],
    termsAndConditions: "<p>Bookings minimum 2 weeks in advance</p><p></p>",
    storyLineKeywords: [
      "Paris Opera House",
      "Ballet",
      "Fashion",
      "Costumes Workshop",
      "Backstage Visit",
      "Palais Garnier",
      "Paris Ballet",
      "Exclusive visit",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66002ec23b3a2d7cf3c2c344",
    title:
      "Bastille's Set Design Workshops (Carpentry, Sculpture, Composite Materials and more)",
    vendorId: "660022683b3a2d7cf3c2c340",
    description:
      "<p>Set in a 7,000-square-metre space, the six workshops - carpentry, metalwork, composite materials, sculpture, tapestry and painting - and the design office create the sets for the operas and ballets presented at the Bastille Opera and the Palais Garnier.\n<br>\nAll the elements are later assembled in the assembly area, located between the workshops and the stage area. They are then transported to the stage before the rehearsals begin.\n<br>\nThis special private visit will take you to the heart of the Paris Opera House set design magic. During the visit, you will get to see the sets being built and meet with several of the incredible artists who make the magic happen. It is a truly extraordinary and rare opportunity to see how opera and ballet productions take shape.</p>",
    address: "Opera Bastille - 120 rue de Lyon, 75012 Paris",
    price: ["€3500"],
    duration: ["90 min"],
    availableTime: ["Monday to Friday 11am to 5pm"],
    links: [
      {
        link: "https://www.operadeparis.fr/en/about/theaters-and-workshops/ateliers-decors",
        explanation: "Official Website",
      },
    ],
    linkWithOtherExperience: [
      {
        experienceId: "660028e23b3a2d7cf3c2c342",
        experienceName: "Private Visit of the Opera Bastille",
        why: "Perfect to complete the visit of the Bastille Opera House",
      },
    ],
    termsAndConditions: "<p>Bookings minimum 2 weeks in advance</p>",
    storyLineKeywords: [
      "Paris Opera House",
      "Set design",
      "Workshop",
      "Backstage Visit",
      "Sculpture",
      "Carpentry",
      "Metalwork",
      "Composite Materials",
      "Tapestry",
      "Painting",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66017ee058cd005ba7eb4783",
    title: "Private Visit of the Great Apartments",
    vendorId: "66017d7c58cd005ba7eb4782",
    providers: [],
    description:
      "<p>Discover the castle with an evening private visit to explore the great apartments without the crowds. For this private visit you will be guided by a historian of the castle</p>",
    address: "Chateau de Fontainebleau",
    price: ["€3500"],
    duration: ["90 min"],
    availableTime: ["Monday to Saturday 6pm to 9pm"],
    links: [
      {
        link: "https://www.chateaudefontainebleau.fr/en/10-reasons-to-visit-the-chateau-de-fontainebleau/",
        explanation: "Official Website - 10 reasons to visit Fontainebleau",
      },
    ],
    linkWithOtherExperience: [],
    termsAndConditions: "<p>Bookings minimum 2 weeks in advance</p>",
    storyLineKeywords: [
      "Royal Palace",
      "Fontainebleau",
      "UNESCO World Heritage",
      "Francois I",
      "Louis XIV",
      "Napoleon",
      "Catherine de Medici",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "660180ba58cd005ba7eb4784",
    title: "Private Visit of the Small Apartments",
    vendorId: "66017d7c58cd005ba7eb4782",
    providers: [],
    description:
      "<p>Fontainebleau has many rooms and treasures regular visitors never get to see. With this exclusive private visit, you will discover all the small apartments, including Josephine’s private apartments and Napoleon’s personal library.&nbsp;\nFor this private visit, you will be guided by a historian of the castle.</p>",
    address: "Chateau de Fontainebleau",
    price: ["€3500"],
    duration: ["90 mins", "120 mins", "180 mins"],
    availableTime: ["Monday to Saturday 10am to 6pm", "Sunday 1pm to 6pm"],
    links: [
      {
        link: "https://www.chateaudefontainebleau.fr/en/explore-the-castle-and-gardens/fontainebleau-rooms/fontainebleau-kings/",
        explanation: "Official Website - In the private world of the monarchs",
      },
      {
        link: "https://www.chateaudefontainebleau.fr/le-chateau-et-les-jardins-de-fontainebleau/pieces-fontainebleau/fontainebleau-secret/",
        explanation: "Official Website - Fontainebleau secret",
      },
    ],
    linkWithOtherExperience: [
      {
        experienceId: "66017ee058cd005ba7eb4783",
        experienceName: "Private Visit of the Great Apartments",
        why: "Ideal to visit the entire castle away from the crowds",
      },
    ],
    termsAndConditions: "<p>Bookings minimum 2 weeks in advance</p><p></p>",
    storyLineKeywords: [
      "Napoleon",
      "Josephine",
      "Napoleon III",
      "Saint Louis",
      "Empress Eugenie",
      "Secret visit",
      "Intimate apartments",
      "Exclusive visit",
      "Not Accessible to the General Public",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "660182e458cd005ba7eb4785",
    title: "Private Diner in the Palace",
    vendorId: "66017d7c58cd005ba7eb4782",
    providers: [],
    description:
      "<p>Enjoy the privilege of dining privately in one of the most beautiful rooms in the castle.&nbsp;\nThis exclusive private diner in Fontainebleau is a once-in-a-lifetime gastronomical experience to feel like the Kinds of France.&nbsp;\nA 4-course gastronomic meal specially prepared by a renowned chef will be served for you and your guests\n<br><br></p>",
    address: "Chateau de Fontainebleau",
    price: ["€25000 up to 4 people", "€1000 each additional person (up to 20)"],
    duration: ["2 hour"],
    availableTime: ["Monday to Saturday 7pm to 10pm"],
    links: [
      {
        link: "https://www.chateaudefontainebleau.fr/en/group-space/associations-and-professionals/exceptional-spaces-2/",
        explanation: "Official Website",
      },
    ],
    linkWithOtherExperience: [
      {
        experienceId: "66017ee058cd005ba7eb4783",
        experienceName: "Private Visit of the Great Apartments",
        why: "Perfect to end the visit with an incredible gastronomic experience in the palace",
      },
      {
        experienceId: "660180ba58cd005ba7eb4784",
        experienceName: "Private Visit of the Small Apartments",
        why: "A great way to end the visit ",
      },
    ],
    termsAndConditions: "<p>Bookings minimum 6 weeks in advance</p>",
    storyLineKeywords: [
      "Private Diner",
      "Exclusive Experience",
      "Gastronomy",
      "Fontainebleau",
      "Napoleon",
      "Louis XIV",
      "Francis I",
      "UNESCO World Heritage",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66018a2158cd005ba7eb4786",
    title: "Napoleon in Fontainebleau",
    vendorId: "66017d7c58cd005ba7eb4782",
    providers: [],
    description:
      "<p>Very close to the Cour d’Honneur where Napoleon I bade farewell to his Old Guard on 20 April 1814, there is now a museum dedicated entirely to the First Empire (1804-1814). Bringing together an exceptional collection of furniture, artefacts, paintings, sculptures, weapons, costumes and ceramics, this museum with more than 500 works, is all about Napoleon I's ten-year reign. Opened in 1986 in the Louis XV wing at the château, where the Military Academy of Fontainebleau was formerly housed, in the 10 rooms of the museum you will discover the Napoleonic era, his journey from the coronation in 1804 to the abdication at Fontainebleau in April 1814.\n<br>\nDuring this dedicated private visit, you will get to visit this new museum, all the Napoleon rooms of the Palace, and discover some hidden treasures of Emperor Napoleon</p>",
    address: "Chateau de Fontainebleau",
    price: ["€5500"],
    duration: ["2 hour"],
    availableTime: ["Monday to Sunday 3pm to 7pm"],
    links: [
      {
        link: "https://www.chateaudefontainebleau.fr/en/explore-the-castle-and-gardens/fontainebleau-rooms/napoleon-museum-fontainebleau/",
        explanation: "Official Website - Napoleon Museum",
      },
    ],
    linkWithOtherExperience: [
      {
        experienceId: "66017ee058cd005ba7eb4783",
        experienceName: "Private Visit of the Great Apartments",
        why: "Completes the visit of the castle beyond Napoleon",
      },
      {
        experienceId: "660182e458cd005ba7eb4785",
        experienceName: "Private Diner in the Palace",
        why: "The Private Diner can take place in a room related with Napoleon",
      },
    ],
    termsAndConditions: "<p>Bookings minimum 2 weeks in advance</p>",
    storyLineKeywords: [
      "Napoleon",
      "French Revolution",
      "Pope Pius VII",
      "Napoleon Coronation",
      "Napoleon Abdication",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66018bb258cd005ba7eb4787",
    title: "Play Real Tennis in Fontainebleau (Jeu de Paume)",
    vendorId: "66017d7c58cd005ba7eb4782",
    providers: [],
    description:
      "<p>The Château de Fontainebleau has one of the few active Jeu de Paume in France. in France. </p><p>Henri IV, like other sovereigns and the best players of their time played memorable games in this room. </p><p>This is an incredible opportunity to discover the Real Tennis (Jeu de Paume) with a master of the game and then either learn or play a game if you are already an experienced player.</p>",
    address: "Chateau de Fontainebleau",
    price: [],
    duration: [],
    availableTime: [],
    links: [
      {
        link: "https://fr-fr.facebook.com/CercleDuJeuDePaumeDeFontainebleau",
        explanation: "Cercle Du Jeu D ePaume De Fontainebleau Facebook",
      },
    ],
    linkWithOtherExperience: [],
    termsAndConditions: "<p>Bookings minimum 2 weeks in advance</p>",
    storyLineKeywords: [],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66018f1458cd005ba7eb4789",
    title: "Private Hot Air Balloon in Paris and Fontainebleau",
    vendorId: "66018cdc58cd005ba7eb4788",
    providers: [],
    description:
      "<p>Paris area – Fontainebleau Balloon Ride – From the splendour of the castle to the splendour of the forest! </p><p>Crowned heads and renowned artists have frequented, even adopted, the city and its surroundings. As you fly over this haven of peace, a few kilometres from the hustle and bustle of the capital, the choice of this destination is obvious. The spectacle is simply awe-inspiring. No doubt the Sun King himself would have tasted the attraction. With the wind, the landscapes pass by: Moret-sur-Loing, the small medieval town; the bocage of Gâtinais, the valleys of the Seine, Yonne or Loing dotted with its many locks. From the basket, the Ile de France reveals forgotten and sometimes even unsuspected charms. This destination is the promise of an enchanted break in the life of a day-long aeronaut.</p>",
    address: "Chateau de Fontainebleau",
    price: ["1300 - 4 people", "2600 - 7-8 people", "3150 - 9-12 people"],
    duration: ["3h service with 1h flight"],
    availableTime: [
      "Sunset from April to the end of October",
      "Sunrise from April to the end of October",
    ],
    links: [
      {
        link: "no",
        explanation: "no",
      },
    ],
    linkWithOtherExperience: [],
    termsAndConditions:
      "<p>Bookings minimum 2 weeks in advance\n<br>\nReschedule possible in case of bad weather \n<br>\nTo make refunds, the cancellation insurance is already included in your purchase. It is individual and costs 25€ per person.\n<br>\nThis insurance allows you to cancel for any reason at least 3 days before the flight date and to be reimbursed or to be refunded in case of bad weather on the day of the flight (cancellation on our part).\n<br>\nOnly the price of the ticket is refunded, the €25 for the cancellation insurance is non-refundable.</p>",
    storyLineKeywords: [
      "Fontainebleau Palace",
      "Forest",
      "UNESCO World Heritage",
      "Hot Air Balloon",
      "Paris",
      "Castles",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66095ad16f27e110abe65e0a",
    title: "The Giacometti Notebooks",
    vendorId: "66095a516f27e110abe65e09",
    providers: [],
    description:
      "<p>Seeing the Giacometti's Notebooks in the private house</p>",
    address: "Institute Giacometti",
    price: ["€5000"],
    duration: ["90 mins"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    linkWithOtherService: [],
    termsAndConditions: "",
    storyLineKeywords: [
      "Guicametti",
      "Art",
      "Sculpture",
      "Notebooks",
      "Drawing Notebooks",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "660e92c83d5b54074f9aaa2f",
    title: "Private Visit of the Great Apartments.",
    vendorId: "65ff02c2e1b82f7ea737f8e3",
    providers: [],
    description:
      "<p>Despite only a small fraction of the Palace of Versailles is&nbsp;open to the public, several incredible and intimate rooms can be accessible on a private visit. These are the small apartments.&nbsp;</p><p>As there are countless incredible hidden rooms, it is possible to select a few to create a thematic visit. Of course, several themes can be linked together.</p>",
    address: "Palace of Versailles - France",
    price: ["€10000"],
    duration: ["90 mins"],
    availableTime: ["Monday to Sunday 6pm to 9:30pm"],
    links: [
      {
        link: "https://en.chateauversailles.fr/discover/estate/palace",
        explanation: "Official website",
      },
    ],
    linkWithOtherExperience: [],
    linkWithOtherService: [
      {
        serviceId: "65ff2a1c8302531638e3971b",
        serviceName: "Private Fireworks",
        why: "Name",
      },
      {
        serviceId: "65ff2c158302531638e3971d",
        serviceName: "Private Royal Entrance",
        why: "Name",
      },
      {
        serviceId: "65ff2a1c8302531638e3971b",
        serviceName: "Private Fireworks",
        why: "Name2",
      },
      {
        serviceId: "65ff2c158302531638e3971d",
        serviceName: "Private Royal Entrance",
        why: "Name2",
      },
      {
        serviceId: "65ff2a1c8302531638e3971b",
        serviceName: "Private Fireworks",
        why: "Name3",
      },
    ],
    termsAndConditions:
      "<p>Booking maximum 3 weeks before</p><p>Not suitable for wheelchair&nbsp;</p>",
    storyLineKeywords: [
      "Versailles",
      "Marie Antoinette",
      "Louis XIV",
      "Louis XV",
      "Louis XVI",
      "French Revolution",
      "Royal Palace",
      "Secret Rooms",
    ],
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66164d43d29b6f258ba3d202",
    title: "The Declaration of the Rights of Man and of the Citizen",
    vendorId: "66017c8558cd005ba7eb4781",
    providers: [],
    description:
      "<p>Inspired by the American Declaration of Independence in 1776 and the spirit of the Enlightenment, the Declaration of the Rights of Man and of the Citizen of 1789 marked the beginning of a new political era. Since then, it has never ceased to be a reference text. </p><p>The French Republic explicitly states its attachment to it, citing it in the preamble of its Constitution, and the Constitutional Council recognized its constitutional value in 1971.  </p><p>The Declaration of the Rights of Man and of the Citizen came into existence in the summer of 1789, born of an idea of the Constituent Assembly, which was formed by the assembly of the Estates General to draft a new Constitution, and precede it with a declaration of principles. &nbsp; There were many proposals. The Constituent Assembly tasked five deputies – Démeunier, La Luzerne, Tronchet, Mirabeau et Redon – with examining the various draft declarations, combining them into a single one and presenting it to the Assembly. Article by article, the French declaration was voted on between 20 and 26 August 1789. In its preamble and its 17 articles, it sets out the “natural and inalienable” rights, which are freedom, ownership, security, resistance to oppression; it recognizes equality before the law and the justice system, and affirms the principle of separation of powers.<br><br>During this highly exclusive experience, you will get the rare privilege of seeing the original of the&nbsp;Declaration of the Rights of Man and of the Citizen, as well as several authentic preparatory drafts and historical documents. These documents are not just a treasure of France but of mankind.&nbsp;<br><br></p>",
    address: "60 rue des Francs-Bourgeois, 75003 Paris",
    price: ["€25000"],
    duration: ["90 mins"],
    availableTime: ["Monday to Friday 10am to 5pm", "Saturday 10am to 4pm"],
    links: [
      {
        link: "https://www.elysee.fr/en/french-presidency/the-declaration-of-the-rights-of-man-and-of-the-citizen#:~:text=History-,The%20Declaration%20of%20the%20Rights%20of%20Man%20and%20of%20the,There%20were%20many%20proposals.",
        explanation: "French Presidency - Declaration text and explanation",
      },
    ],
    linkWithOtherExperience: [],
    termsAndConditions:
      "<p>Booking more than 2 months in advance</p><p>Security clearance is needed in advance. A valid ID of all participants must be provided with the booking and shown the day of the experience.</p>",
    storyLineKeywords: [
      "Human Rights",
      "Declaration of the Rights of Man and of the Citizen",
      "History",
      "French Revolution",
      "American Independence ",
      "La Fayette",
      "Thomas Jefferson",
      "Historical Document",
    ],
    memberShip: "platinum",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66164d4bd29b6f258ba3d203",
    title: "Marie Antoinette's Trial",
    vendorId: "66017c8558cd005ba7eb4781",
    providers: [],
    description:
      '<p>On 14th October 1793, Marie-Antoinette was taken to the revolutionary tribunal located at the Conciergerie. After the discovery of a plot for her escape, the Comity of Public Safety decided to expedite the trial and gave the Queen and her lawyers one day to prepare for her defense... Whether one feels for Marie or not, one must admit her trial was a mockery of justice. Her son, the Dauphin - who would have been Louis XVII - was brainwashed and "confessed" he had been abused by his mom... Marie-Antoinette refused to answer that accusation appealing to all mothers in the room.</p><p>During this experience you will have the rare privilege of seeing the original documents of Marie Antoinette\'s trial and the act sentencing her to death. An incredible piece of history through authentic documents and notes never shown to the public.</p>',
    address: "60 rue des Francs-Bourgeois, 75003 Paris",
    price: ["€7500"],
    duration: ["90 mins"],
    availableTime: ["Monday to Friday 10am to 5pm", "Saturday 10am to 4pm"],
    links: [],
    linkWithOtherExperience: [
      {
        experienceId: "66164d43d29b6f258ba3d202",
        experienceName:
          "The Declaration of the Rights of Man and of the Citizen",
        why: "These are both key events of the French Revolution",
      },
    ],
    linkWithOtherService: [],
    termsAndConditions:
      "<p>Booking more than 1 month in advance</p><p>Security clearance is needed in advance. A valid ID of all participants must be provided with the booking and shown the day of the experience.</p>",
    storyLineKeywords: [
      "Declaration of the Rights of Man and of the Citizen",
      "History",
      "French Revolution",
      "Historical Document",
      "Marie Antoinette",
      "Louis XVI",
      "Historic Trial",
    ],
    memberShip: "gold",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66164f1fd29b6f258ba3d204",
    title: "Trials of the Knights Templar",
    vendorId: "66017c8558cd005ba7eb4781",
    providers: [],
    description:
      "<p>In 1307, members of the&nbsp;Knights Templar&nbsp;in the&nbsp;Kingdom of France&nbsp;were suddenly charged with&nbsp;heresy and arrested after their leader, Master&nbsp;Jacques de Molay, had recently come to France for meetings with&nbsp;Pope Clement V.[1]&nbsp;Many, including their leader, were&nbsp;burned at the stake&nbsp;while others were sentenced to&nbsp;perpetual imprisonment. The events in France led to a series of trials in other locations, not all of which had the same outcome.</p><p>During this experience, you will have the rare privilege of seeing the original documents of the biggest sham trial in history to discover the&nbsp;real story of one of the most important moments in medieval history and it's consequences through Europe and the world.</p>",
    address: "60 rue des Francs-Bourgeois, 75003 Paris",
    price: ["€9500"],
    duration: ["90 mins"],
    availableTime: ["Monday to Friday 10am to 5pm", "Saturday 10am to 4pm"],
    links: [],
    linkWithOtherExperience: [],
    linkWithOtherService: [],
    termsAndConditions:
      "<p>Booking more than 1 month in advance</p><p>Security clearance is needed in advance. A valid ID of all participants must be provided with the booking and shown the day of the experience.</p>",
    storyLineKeywords: [
      "History",
      "Historical Document",
      "Historic Trial",
      "Knights Templar",
      "Jacques de Molay",
      "Medieval History",
      "Templar's Treasure",
    ],
    memberShip: "gold",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66165ec7d29b6f258ba3d207",
    title: "The Prisse Papyrus",
    vendorId: "66165bf5d29b6f258ba3d206",
    providers: [],
    description:
      "<p>The&nbsp;Prisse Papyrus&nbsp;is an&nbsp;ancient Egyptian&nbsp;papyrus datable to the&nbsp;Middle Kingdom which was discovered by the inhabitants of Kurna and given to French orientalist&nbsp;Émile Prisse d'Avennes&nbsp;at&nbsp;Thebes&nbsp;and published in 1847. It is the oldest known papyrus in the world.<br>Inhabitants of&nbsp;Kurna&nbsp;originally found the papyrus inside the&nbsp;rishi coffin&nbsp;of&nbsp;pharaoh&nbsp;Sekhemre-Wepmaat Intef&nbsp;of the&nbsp;17th Dynasty, whose tomb was probably located in&nbsp;Dra' Abu el-Naga'&nbsp;near Thebes. The&nbsp;papyrus&nbsp;document contains the last two pages of the&nbsp;Instructions of Kagemni, who purportedly served under pharaoh&nbsp;Sneferu&nbsp;of the&nbsp;4th Dynasty, and is a compilation of moral maxims and admonitions on the practice of virtue (sebayt). The conclusion of the&nbsp;Instructions of Kagemni&nbsp;is followed by the only complete surviving copy of the&nbsp;Instruction of Ptahhotep.</p>",
    address: "",
    price: ["€2500"],
    duration: ["60 mins"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions: "<p>Bookings 1 month minimum</p>",
    storyLineKeywords: [
      "Prisse Papyrus",
      "Papyrus",
      "Ancient Egypt",
      "Historical Treasure",
    ],
    memberShip: "silver",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "661660d7d29b6f258ba3d208",
    title: "The Dead Sea Scrolls",
    vendorId: "66165bf5d29b6f258ba3d206",
    providers: [],
    description:
      "<p>This discovery, which was considered to be the most important archaeological find in the 20th century, continues to question the foundations of Judaism and Christianity, which are now more than ever conjoined by this mysterious library, buried in the desert.</p><p>During this experience, you will get the rare chance to see the Death Sea Scrolls and other related precious manuscripts in the company of the head the Department of Oriental Manuscripts.</p>",
    address: "",
    price: ["€5000"],
    duration: [],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions: "<p><br></p>",
    storyLineKeywords: ["Dead Sea Scrolls", "Bible", "Judaism", "Christianity"],
    memberShip: "",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66531f778a9da42182f41cbf",
    title:
      "Historical 18th century dining experience at the Palace of Versailles",
    vendorId: "65ff3ef38302531638e3972c",
    providers: [
      {
        providerId: "65ff3fb68302531638e3972e",
        providerName: "Tables d'Exception",
      },
    ],
    description: "",
    address: "",
    price: ["10000"],
    duration: ["90min"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions: "",
    storyLineKeywords: ["Versailles", "Historical Diner", "Gastronomy"],
    memberShip: "",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66531f848a9da42182f41cc0",
    title:
      "Historical 18th century dining experience at the Palace of Fontainebleau",
    vendorId: "65ff3ef38302531638e3972c",
    providers: [
      {
        providerId: "65ff3fb68302531638e3972e",
        providerName: "Tables d'Exception",
      },
    ],
    description: "",
    address: "",
    price: ["10000"],
    duration: ["90min"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    linkWithOtherService: [],
    termsAndConditions: "",
    storyLineKeywords: ["Historical Diner", "Gastronomy", "Fontainebleau"],
    memberShip: "",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "661660d7d29b6f258ba3d243",
    title: "The sandy beaches of Cabourg",
    vendorId: "66165bf5d29b6f258ba3d206",
    providers: [],
    description:
      "<p>The atmosphere of the town brings the Golden age to mind with the casino, the racecourse and the array of villas on the seafront. The beach bordering the vast Marcel Proust promenade stretches over 4 km of fine sand. Cabourg is also a cultural destination with its Romantic Film Festival or the Music Festival, Cabourg Mon Amour.</p>",
    address: "",
    price: ["€5000"],
    duration: [],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions: "<p><br></p>",
    storyLineKeywords: ["Dead Sea Scrolls", "Bible", "Judaism", "Christianity"],
    memberShip: "",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "668418396a21633d18f4a7ca",
    title: "Breakfast, Apéritif or Tea at the Moulin with an art expert",
    vendorId: "668417096a21633d18f4a7c9",
    providers: [],
    description:
      '<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #18191a"><span style="color: #000000">Discover Montmartre’s last windmill, a place full of history and art immortalised by Auguste Renoir in his famous </span>painting, <a href="https://en.wikipedia.org/wiki/Bal_du_moulin_de_la_Galette"><span style="text-decoration: underline ; color: #000000">Bal du moulin de la Galette</span></a>. As you enjoy an apéritif or an afternoon tea in this iconic place, you will meet with and expert to learn and discuss about Montmartre, the famous artists that lived close by and experience a taste of the bohemian life they had back in the 19th century.</p>\n<br class="Apple-interchange-newline">',
    address: "Moulin de la Galette",
    price: ["€250 for 2", "€75 each extra person"],
    duration: ["1h", "1h30", "2h"],
    availableTime: ["Tuesday to Sunday"],
    links: [
      {
        link: "https://en.wikipedia.org/wiki/Moulin_de_la_Galette",
        explanation: "History on Wikipedia",
      },
      {
        link: "https://www.moulindelagaletteparis.com/ ",
        explanation: "Official Website",
      },
    ],
    linkWithOtherExperience: [],
    termsAndConditions:
      '<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">Suitable for all ages</p>\n<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">Bookings &gt;24h depending on availability</p>\n<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">Experience Payment terms: Downpayment 30% - 20% 7 days prior - 50% on completion</p>\n<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">Experts payment terms: Downpayment 50% - 50% upon completion</p>\n<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">Allergies and dietary restrictions needed 24h prior.<span class="Apple-converted-space">&nbsp;</span></p><p></p>',
    storyLineKeywords: [
      "Montmartre",
      "Impressionists ",
      "Famous Artists",
      "Van Gogh",
      "Renoir",
      "Degas",
      "Toulouse Lautrec",
      "Incredible location",
      "Windmill",
      "Historical restaurant",
    ],
    memberShip: "bronze",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "668419f46a21633d18f4a7ce",
    title: "Private lunch in Theo Van Gogh’s apartment ",
    vendorId: "668419436a21633d18f4a7cd",
    providers: [],
    description:
      '<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">Enjoy the rare privilege of visiting Theo Van Gogh’s apartment where his brother Vincent lived and work when he was living in Paris. This is an incredible opportunity to be were Van Gogh lived. Today, this apartment is a private property not accessible to the public and never visited, but on this occasion, the owners will host you for a lunch to speak about Van Gogh and the Montmartre of the Impressionists. <span class="Apple-converted-space">&nbsp;</span></p>',
    address: "54 rue Lepic, 75018 Paris",
    price: ["€2500 for 2"],
    duration: ["90 min", "120 min"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions:
      '<ul style="list-style-type: \'—&nbsp;&nbsp;\'">\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Not suitable for children under 7</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Not suitable for disable people or elderly people because there’s 2 flights of stairs and no elevator.<span class="Apple-converted-space">&nbsp;</span></li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Bookings &gt;5 days depending on availability</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Venue Payment terms: Downpayment 30% - 70% on completion</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Chefs payment terms: Downpayment 50% - 50% upon completion</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Menu (and wine) payment terms : 100% 72h prior</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Allergies and dietary restrictions needed 5 days prior.<span class="Apple-converted-space">&nbsp;</span></li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Client needs to approve menu on the platform within a given time</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>No approval from the client equals acceptance.</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>No changes in menu possible &gt;72h prior</li>\n</ul><p><br></p>',
    storyLineKeywords: [
      "Van Gogh",
      "Theo Van Gogh",
      "Montmartre",
      "Historical hidden place",
      "Private apartment",
      "VIP",
      "Gastronomy",
      "Wine tasting",
    ],
    memberShip: "gold",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66841bb06a21633d18f4a7d0",
    title:
      "Walking tour of Montmartre in the footsteps of the artists that lived there and those still living there",
    vendorId: "66841a4c6a21633d18f4a7cf",
    providers: [],
    description:
      "<p style=\"margin: 0.0px 0.0px 0.0px 0.0px; font: 9.0px 'Helvetica Neue'; color: #000000\">Explore the artists that lived in Montmartre in the 19th century, most of all the Impressionists such as Van Gogh, Renoir, Degas, Gaugin, Toulouse Lautrec and others.</p><p style=\"margin: 0.0px 0.0px 0.0px 0.0px; font: 9.0px 'Helvetica Neue'; color: #000000\">During this private walking tour we will explore Montmartre's famous landmarks but also countless hidden places that are part of the rich history of this iconic neighbourhood. We will retrace the lives and friendships of those artists and explore how Montmartre because to be the central point of the Impressionist movement.&nbsp;</p><p><br></p>",
    address: "Montmartre",
    price: ["€250 for 2"],
    duration: ["90 min"],
    availableTime: ["Monday to Saturday from 11h30 to 21h30"],
    links: [],
    linkWithOtherExperience: [],
    linkWithOtherService: [],
    termsAndConditions: "",
    storyLineKeywords: [
      "Montmartre",
      "Famous Artists",
      "Living Artists",
      "Impressionists ",
      "Van Gogh",
      "Toulouse Lautrec",
      "Degas",
      "Renoir",
      "Gauguin ",
      "Pizarro",
      "Satie",
      "Suzanne Valadon",
      "Utrillo",
      "Picasso",
    ],
    memberShip: "bronze",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66841be46a21633d18f4a7d1",
    title:
      "Walking tour to explore Montmartre at the begining of the 20th century ",
    vendorId: "66841a4c6a21633d18f4a7cf",
    providers: [],
    description:
      "<p style=\"margin: 0.0px 0.0px 0.0px 0.0px; font: 9.0px 'Helvetica Neue'; color: #000000\">Explore Montmartre at the begining of the 20th century until the artists left and relocated to Montparnasse and learn about famous artists such as Degas, Picasso, Matisse, Braque and many more</p><p style=\"margin: 0.0px 0.0px 0.0px 0.0px; font: 9.0px 'Helvetica Neue'; color: #000000\">During this private walking tour we will explore Montmartre's famous landmarks but also countless hidden places that are part of the rich history of this iconic neighbourhood. We will retrace the lives and friendships of those artists.</p><p><br></p>",
    address: "Montmartre",
    price: ["€250 for 2"],
    duration: ["90 min"],
    availableTime: ["Monday to Saturday from 11h30 to 21h30"],
    links: [],
    linkWithOtherExperience: [],
    linkWithOtherService: [],
    termsAndConditions: "",
    storyLineKeywords: [
      "Montmartre",
      "Famous Artists",
      "Living Artists",
      "Impressionists ",
      "Van Gogh",
      "Toulouse Lautrec",
      "Degas",
      "Renoir",
      "Gauguin ",
      "Pizarro",
      "Satie",
      "Suzanne Valadon",
      "Utrillo",
      "Picasso",
    ],
    memberShip: "bronze",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66841d966a21633d18f4a7d3",
    title: "The Renoir Gardens",
    vendorId: "66841cc46a21633d18f4a7d2",
    providers: [],
    description:
      '<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">Discover one of the most picturesque hidden gardens in Paris, belonging to the house where many famous artists lived and painted. Among them was Auguste Renoir, who resided here between 1875 and 1877 and painted several masterpieces, including the famous "Le Bal du Moulin de la Galette" ("The Moulin de la Galette Ball"), "La Balançoire" ("The Swing"), and "Jardin de la rue Cortot" ("Rue Cortot Garden"). A moment to relax and feel as if you had travelled back in time to the era of Impressionism.<span class="Apple-converted-space">&nbsp;</span></p>',
    address: "Musée de Montmartre",
    price: ["€200 up to 4 people"],
    duration: ["90 min", "60 min", "120 min"],
    availableTime: [],
    links: [
      {
        link: "https://museedemontmartre.fr/en/musee-jardins/ ",
        explanation: "official website",
      },
    ],
    linkWithOtherExperience: [],
    termsAndConditions: "",
    storyLineKeywords: [
      "Montmatre",
      "Impressionists",
      "Renoir",
      "Toulouse Lautrec",
      "Suzanne Valadon",
      "Utrillo",
      "Van Gogh",
      "Hidden Garden",
      "Historical landmark",
    ],
    memberShip: "bronze",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66841d9c6a21633d18f4a7d4",
    title: "Private Visit to the Renoir Gardens",
    vendorId: "66841cc46a21633d18f4a7d2",
    providers: [],
    description:
      '<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">Discover privately one of the most picturesque hidden gardens in Paris, belonging to the house where many famous artists lived and painted. Among them was Auguste Renoir, who resided here between 1875 and 1877 and painted several masterpieces, including the famous "Le Bal du Moulin de la Galette" ("The Moulin de la Galette Ball"), "La Balançoire" ("The Swing"), and "Jardin de la rue Cortot" ("Rue Cortot Garden"). A moment to relax and feel as if you had travelled back in time to the era of Impressionism.<span class="Apple-converted-space"><br></span>This experience could be coupled with a visit (or private visit) to the museum, a private visit to the Montmartre Vineyards, the famous Lapin Agile cabaret or even an art private lesson in Suzanne Valadon’s historical workshop.</p>\n<br class="Apple-interchange-newline"><p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span class="Apple-converted-space"><br></span></p>',
    address: "Musée de Montmartre",
    price: ["€4000 up to 8 people"],
    duration: ["90 min", "60 min", "120 min"],
    availableTime: [],
    links: [
      {
        link: "https://museedemontmartre.fr/en/musee-jardins/ ",
        explanation: "official website",
      },
    ],
    linkWithOtherExperience: [],
    linkWithOtherService: [],
    termsAndConditions: "",
    storyLineKeywords: [
      "Montmatre",
      "Impressionists",
      "Renoir",
      "Toulouse Lautrec",
      "Suzanne Valadon",
      "Utrillo",
      "Van Gogh",
      "Hidden Garden",
      "Historical landmark",
    ],
    memberShip: "silver",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "668422656a21633d18f4a7d6",
    title: "Evening Private Visit",
    vendorId: "66841e426a21633d18f4a7d5",
    providers: [],
    description:
      '<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">Discover the iconic Louis Vuitton Foundation during a prestigious private visit with an expert art historian. A privilege for the very few.</p>\n<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">This private visit is the opportunity to discover the Foundation’s permanent collections, it’s current exhibition and Frank Gehry’s architectural masterpiece. You will enjoy a VIP meet and greet with champagne upon arrival and then a visit that can be tailored in countless ways.</p>\n<br class="Apple-interchange-newline"><p></p>',
    address: "Fondation Louis Vuitton",
    price: ["€22,000 for up to 10 people"],
    duration: ["90 min"],
    availableTime: ["Monday to Saturday from 20h to 23h45"],
    links: [
      {
        link: "https://www.fondationlouisvuitton.fr/fr/collection ",
        explanation: "Official website of the collection",
      },
    ],
    linkWithOtherExperience: [],
    termsAndConditions:
      '<ul style="list-style-type: \'—&nbsp;&nbsp;\'">\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Not suitable for children under 12</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Suitable for disable people and elderly people</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Bookings &gt;2 weeks depending on availability</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Venue Payment terms: Downpayment 50% - 30% 10 days prior and 20% on completion</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Catering payment terms: Downpayment 70% - 30% upon completion</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Allergies and dietary restrictions needed 10 days prior.<span class="Apple-converted-space">&nbsp;</span></li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Client needs to approve menu on the platform within a given time</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>No approval from the client equals acceptance.</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>No changes in menu possible &gt;5 days prior</li>\n</ul><p><br></p>',
    storyLineKeywords: [
      "Modern Art",
      "Contemporary Art",
      "Art Foundation",
      "Art Collection",
      "Art Exhibition",
    ],
    memberShip: "silver",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "668422696a21633d18f4a7d7",
    title: "Private Dinner with Van Gogh's Descendants ",
    vendorId: "66841e426a21633d18f4a7d5",
    providers: [],
    description:
      '<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">After a private visit or on it\'s own, enjoy the privilege of dining in the middle of the collections with the descendants of Van Gogh.</p><p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">During this extraordinary gastronomic dinner, a renewed chef will prepare a tasting menu for you and your guests. On top of that, the Foundation will invite Van Gogh’s great-grandnephew&nbsp;</p>\n<br class="Apple-interchange-newline"><p></p>',
    address: "Fondation Louis Vuitton",
    price: ["€13000 up to 10 people"],
    duration: ["90 min", "90 min"],
    availableTime: ["Monday to Saturday from 20h to 23h45"],
    links: [
      {
        link: "https://www.fondationlouisvuitton.fr/fr/collection ",
        explanation: "Official website of the collection",
      },
    ],
    linkWithOtherExperience: [
      {
        experienceId: "668422656a21633d18f4a7d6",
        experienceName: "Evening Private Visit",
        why: "Perfect combination ",
      },
    ],
    linkWithOtherService: [],
    termsAndConditions:
      '<ul style="list-style-type: \'—&nbsp;&nbsp;\'">\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Not suitable for children under 12</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Suitable for disable people and elderly people</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Bookings &gt;2 weeks depending on availability</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Venue Payment terms: Downpayment 50% - 30% 10 days prior and 20% on completion</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Catering payment terms: Downpayment 70% - 30% upon completion</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Allergies and dietary restrictions needed 10 days prior.<span class="Apple-converted-space">&nbsp;</span></li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>Client needs to approve menu on the platform within a given time</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>No approval from the client equals acceptance.</li>\n<li style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000"><span style="font: 13.2px \'Helvetica Neue\'"></span>No changes in menu possible &gt;5 days prior</li>\n</ul><p><br></p>',
    storyLineKeywords: [
      "Modern Art",
      "Contemporary Art",
      "Art Foundation",
      "Art Collection",
      "Art Exhibition",
      "Van Gogh",
      "Gastronomy",
      "Private Dinner",
      "VIP",
    ],
    memberShip: "gold",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66bb69f85c81e763ff95a228",
    title: "VIP Style and Shopping Experience",
    vendorId: "66bb697d5c81e763ff95a227",
    providers: [],
    description:
      '<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">For this exclusive experience place Vendôme, you will get access to the flagship historic VIP apartment for a lesson in style with one of the creatives of the brand.</p>\n<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">Away from the average private shopping experience, this time, it is one of the creative minds behind the fashion collections which will be your stylist, all with a treatment reserved to celebrities and royalty.<span class="Apple-converted-space">&nbsp;</span></p>',
    address: "Louis Vuitton Place Vendome",
    price: [],
    duration: ["90 mins"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions: "",
    storyLineKeywords: [
      "Louis Vuitton",
      "Fashion",
      "Shopping",
      "Luxury",
      "Style",
    ],
    memberShip: "gold",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66bb6a585c81e763ff95a229",
    title: "A peek at Vuitton’s couture workshops",
    vendorId: "66bb697d5c81e763ff95a227",
    providers: [],
    description:
      "<p style=\"margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px 'Helvetica Neue'; color: #000000\">Have you ever wanted to peek behind the scenes and see where one of the most famous fashion brands in the world creates the fabulous gowns worn by famous celebrities in Cannes, the Oscars, the Met Gala and other high profile events? Well, now you can.</p>\n<p style=\"margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px 'Helvetica Neue'; color: #000000; min-height: 12.0px\"><br></p>\n<p style=\"margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px 'Helvetica Neue'; color: #000000\">During this ultra-exclusive experience, you will get to meet with Vuitton’s head of atelier who will open you the doors of the highly confidential Rarex workshops, Place Vendôme And show you how they create these incredible gowns.</p>",
    address: "Louis Vuitton Place Vendôme ",
    price: [],
    duration: ["90 mins"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions: "",
    storyLineKeywords: [
      "Louis Vuitton",
      "Haute Couture",
      "Bespoke Fashion",
      "Fashion",
      "High Fashion",
      "Shopping",
      "Luxury",
    ],
    memberShip: "platinum",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66bb6b975c81e763ff95a22b",
    title: "Private Visit to the historic home of the Vuitton family ",
    vendorId: "66bb697d5c81e763ff95a227",
    providers: [],
    description:
      '<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">Enjoy the privilege of accessing the historic home of the Vuitton family where everything began in 1854.<span class="Apple-converted-space"></span></p>\n<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">This house in the suburbs of Paris is perhaps the most confidential place of the famous trunk maker as it never opens to the public.</p>\n<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">Today, the house belongs to LVHM and has been beautifully preserved, just as if the family had gone away on holiday.</p>\n<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000; min-height: 12.0px"><br></p>\n<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">During this exceptional private you will be privy to the family history and legacy, and meet with a leading figure of the heritage division of Louis Vuitton</p>',
    address: "Louis Vuitton Asnieres",
    price: [],
    duration: ["90 mins"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions: "",
    storyLineKeywords: [
      "Louis Vuitton",
      "Historic House",
      "Family Home",
      "Private House",
      "Vuitton Heritage",
    ],
    memberShip: "gold",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66bb6b9c5c81e763ff95a22c",
    title:
      "Private visit and lunch at the historic home of the Vuitton family ",
    vendorId: "66bb697d5c81e763ff95a227",
    providers: [],
    description:
      '<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">Enjoy the privilege of accessing the historic home of the Vuitton family where everything began in 1854 for a private visit and a gastronomic lunch</p>\n<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">This house in the suburbs of Paris is perhaps the most confidential place of the famous trunk maker as it never opens to the public.</p>\n<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">Today, the house belongs to LVHM and has been beautifully preserved, just as if the family had gone away on holiday.</p>\n<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000; min-height: 12.0px"><br></p>\n<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px \'Helvetica Neue\'; color: #000000">During this exceptional private you will be privy to the family’s history and legacy, and meet with a leading figure of the heritage division of Louis Vuitton. Then, a gastronomic lunch will be served and hosted by the last living descendant of the Vuitton family.</p>\n<br class="Apple-interchange-newline">',
    address: "Louis Vuitton Asnieres",
    price: [],
    duration: ["90 mins"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    linkWithOtherService: [],
    termsAndConditions: "",
    storyLineKeywords: [
      "Louis Vuitton",
      "Historic House",
      "Family Home",
      "Private House",
      "Vuitton Heritage",
      "Gastronomy",
      "Private Lunch",
    ],
    memberShip: "gold",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66bb6d475c81e763ff95a22f",
    title: "Backstage of an Haute Couture Show",
    vendorId: "66bb6c865c81e763ff95a22d",
    providers: [],
    description:
      "<p>This unique experience will take you behind the scenes of the Haute Couture show of one of the best French fashion designers, Alexis Mabille.\n<br>\nYour experience will start 2 days before the show at Alexis workshop to meet with him and his team to see how some the gowns that will be unveiled in the show are being prepared.\n<br>\nThen, on the D-day, you will be invited to see the last preparations of the show a few hours before greeting the audience and the press. This will be an incredible opportunity to see how the models prepare and receive the last instructions.\n<br>\nFinally, you will seat with Alexis personal VIP guests to see the show and then get to meet other VIPs on stage, after the show.</p>",
    address: "Variable",
    price: [],
    duration: ["90mins"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions: "",
    storyLineKeywords: [
      "Fashion",
      "Haute Couture",
      "High Fashion",
      "Fashion Show",
      "Fashion Week",
      "Backstage",
      "Celebrity",
      "Runway",
    ],
    memberShip: "",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66bb6df25c81e763ff95a231",
    title: "Vintage Stylism Experience",
    vendorId: "66bb6d935c81e763ff95a230",
    providers: [],
    description:
      "<p>Join a renowned Parisian fashion collector for an incredible experience to learn about style and get some iconic vintage pieces from the greatest designers.\nThis isn’t a traditional “shopping experience”. It’s a rare opportunity to access the collection of some collectors to learn to style modern clothing with vintage pieces.\n<br>\nDuring this experience you will be able to purchase some of the vintage pieces you like</p>",
    address: "",
    price: [],
    duration: ["90 mins"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions:
      "<p>Exact measurements and size for every participant\n</p><p>Recent pictures of each participant showing their current style\n</p><p>List of expectations (if any) and list of favourite haute couture brands</p>",
    storyLineKeywords: [
      "Fashion",
      "Vintage Fashion",
      "Fashion collection",
      "Shopping",
    ],
    memberShip: "",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66bb6e515c81e763ff95a233",
    title: "Guided visit with a member of the team",
    vendorId: "66bb6e135c81e763ff95a232",
    providers: [],
    description:
      "<p>Enjoy a privileged visit of the Paris zoo with one of the conservationists of the zoo and gain incredible insight on the animals their care and countless stories.</p><p><br></p>",
    address: "Paris Zoo",
    price: [],
    duration: ["2h"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions: "",
    storyLineKeywords: ["Zoo", "Private Visit", "Kinds", "Animals"],
    memberShip: "bronze",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66bb6e685c81e763ff95a234",
    title: "VIP Access to the Animals",
    vendorId: "66bb6e135c81e763ff95a232",
    providers: [],
    description:
      "<p>For those passionate with animals, this is an incredible opportunity to come up close to several of the animals of the zoo, and to take part in their care.&nbsp;\nThis will be a bespoke experience for you to choose your favourite animals - giraffes, hippopotamus, monkeys, penguins, and many more. This experience is ideal for both children and adults.</p>",
    address: "Paris Zoo",
    price: [],
    duration: [],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    linkWithOtherService: [],
    termsAndConditions: "",
    storyLineKeywords: ["Zoo", "Animals", "VIP", "Feeding animals", "Kids"],
    memberShip: "silver",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66c055b6bfc9145a5302d52f",
    title: "Private Visit of Parisian Districts",
    vendorId: "66c0548ebfc9145a5302d52e",
    providers: [],
    description:
      "<p>Let yourself be seduced by a narrated walk in the heart of a Parisian district...<br><br>The capital is full of secret corners, preserved from time and crowds: these districts with a country feel, their poorly paved streets, their alleys flanked by original little houses and their private gardens. During a walk, I will tell you along the streets, the monuments, all the events, the walks, and all the little anecdotes that have made the history of the district... We will take the time to stop on a detail, the name of a street, a setting, a personality...</p><p>You can choose among many classic options such as Saint-Germain-des-Pres, Le Marais, The Islands, the Latin Quarter, but also some off-the-beaten-path such as Pigalle, the Goutte d'Or, Chinatown and many more.&nbsp;</p>",
    address: "",
    price: ["€600"],
    duration: ["90 mins"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions: "",
    storyLineKeywords: [
      "Paris District",
      "Private Walking Tour",
      "Luxury Tour",
    ],
    memberShip: "",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66c05eacbfc9145a5302d53c",
    title: "Paris Gangsters - The atmosphere of the underworld of the 1920s",
    vendorId: "66c0548ebfc9145a5302d52e",
    providers: [],
    description:
      '<p>In the rue de Lappe in the 1920s, some strange guys hung around the neighborhood... They were the "Apaches": bandits, crooks. At the "Bastoche", these bad boys were living their hour of glory. They spent their days between various schemes, swindles and other settling of scores. This original guided tour tells you the story of the gangs of Paris and the sordid past of the Bastille district.<br><br>In dark corners, discover the little-known life of the guys from the Milieu, the tough guys, the real ones, the tattooed ones! At the Bal de la boule rouge and the Balajo, the gangsters danced to musette rhythms. The guys were dressed like lords, their hair shiny with their elegant borsalino. They twirled their "femme fatales" to the sound of the accordion. Immerse yourself in the atmosphere of these shady circles.</p><p>Our tour will end in a confidential Speakeasy with some cocktails.</p>',
    address: "Bastille",
    price: [],
    duration: ["2h"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions: "",
    storyLineKeywords: [
      "Walking Tour",
      "Crime",
      "1920",
      "Gangsters",
      "Speakeasy Bar",
    ],
    memberShip: "bronze",
    _class: "com.mtc.dataentry.model.Experience",
  },
  {
    _id: "66c05f34bfc9145a5302d53d",
    title: "The Villa La Roche - Le Corbusier and modern architecture in Paris",
    vendorId: "66c0548ebfc9145a5302d52e",
    providers: [],
    description:
      "<p>Let's venture into the impasse of Square du Docteur Blanche, in the 16th arrondissement. At the end of a leafy alley, hides a modern building with a white facade: the Maison La Roche. Built between 1923 and 1925, it is the work of the architect Le Corbusier and Pierre Jeanneret. You will appreciate its clean lines, far from the usual refinement of Haussmannian buildings, but which have nevertheless brought a new breath of life to the history of Parisian architecture.<br><br>Its owner, the art lover Raoul La Roche, wanted a large living space to be able to display his rich collection of cubist and purist paintings. His friend Le Corbusier then proposed an innovative architectural project to him. He decided to use new materials, such as reinforced concrete and chose simple geometric shapes. His work is part of the Modern Movement and the house was classified as a Historic Monument in 1996. Lovers of art and architecture, you will feel at home here.</p>",
    address: "",
    price: [],
    duration: ["2h"],
    availableTime: [],
    links: [],
    linkWithOtherExperience: [],
    termsAndConditions: "",
    storyLineKeywords: [
      "Architecture",
      "Modern Architecture",
      "Le Corbusier",
      "Pierre Jeanneret",
    ],
    memberShip: "bronze",
    _class: "com.mtc.dataentry.model.Experience",
  },
];

export default data;
